apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx03
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx03
  template:
    metadata:
      labels:
        app: nginx03
    spec:
      containers:
        - name: nginx03
          image: nginx:stable
          command:
            - /bin/sh
            - -c
            - "echo 'welcome to my web apppppp!' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
      dnsConfig:
        options:
          - name: ndots
            value: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx03
  namespace: default
spec:
  selector:
    app: nginx03
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx03-ingress
  namespace: default
spec:
  ingressClassName: "nginx-internal"
  rules:
    - host: nginx03.k3s.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx03
                port:
                  number: 80
