apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx02
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx02
  template:
    metadata:
      labels:
        app: nginx02
    spec:
      containers:
        - name: nginx02
          image: nginx:stable
          command:
            - /bin/sh
            - -c
            - "echo 'welcome to my web app!' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
      dnsConfig:
        options:
          - name: ndots
            value: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx02
  namespace: default
spec:
  selector:
    app: nginx02
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
