#!/bin/sh
ARGS="--image @bg@"
if [ -z "$1" ]; then
    ARGS="--indicator-radius 0 --indicator-thickness 1 --text-color 00000000 --text-clear-color 00000000 --text-wrong-color 00000000 --text-ver-color 00000000 --separator-color 00000000 --ring-color 00000000 --screenshots --effect-blur 10x10 --effect-vignette 0.8:0.9"
fi

@swaylock@ $ARGS \
    --effect-compose="100,-100;40x40;center;@lock@" \